#!/bin/bash
CUDA_VISIBLE_DEVICES=1 poetry run python scripts/main.py train simplegat \
    --batch_size 500 \
    --tag best-checkpoint \
    --n_channels 128 \
    --n_layers 20 \
    --n_heads 8 \
    --mlp_hidden_channels 256 \
    --mlp_per_gnn_layers 2 \
    --mlp_read_layers 2 \
    --lr 5e-4 \
    --powerflow_weight 1.0 \
    --grad_clip_norm_dual 1.0 \
    --grad_clip_p_dual 2.0 \
    --grad_clip_norm 1.0 \
    --grad_clip_p 2.0 \
    --max_epochs 3000 \
    --patience 5000 \
    --case_name case30_ieee \
    --wd 0.0 \
    --wd_dual_shared 0.0 \
    --wd_dual_pointwise 0.0 \
    --lr_dual_shared 0.01 \
    --lr_dual_pointwise 5e3 \
    --cost_weight 0.1 \
    --multiplier_type pointwise \
    --augmented_weight 5.0 \
    --warmup 250 \
    --supervised_warmup 500 \
    --supervised_weight 10.0 \
    --tag supervised-warmup \
    --tag pointwise \
    --simple_progress